### ISSUE TITLE
Passing URLs to query may not get escaped properly

### ISSUE THREAD

**Issue by Inclushe** [dmlls/yang#1]
Thanks for the shoutout!

I had this same issue with my extension where passing a URL to a site like the Wayback Machine won't get escaped properly. Something like `!wayback https://duckduckgo.com/bangs` works without the extension installed, but with it installed, it tries to search `https%3A%2F%2Fduckduckgo.com%2Fbangs` and fails.

**Comment by dmlls** [comment]
Hi @Inclushe, thank you for your work on DuckDuckGo !Bangs but Faster, and for your issue!

I'm not sure how you solved it, but in my case simply removing the `encodeURIComponent` seems to do the trick.

Do you think this is a good solution or do you think this could lead to unwanted side effects (I do not see any at the moment)?

**Comment by Inclushe** [comment]
It's been a while so I'm not sure if there was an edge case or not. I'd say go ahead and publish the update for now.
