### ISSUE TITLE
add EU and US subdomains for startpage.com

### ISSUE THREAD

**Issue by CrispyPin** [dmlls/yang#24]
**Is your feature request related to a problem? Please describe.**
Yang does not redirect when startpage is set to specifically use EU or US servers, as opposed to the standard www subdomain

**Describe the solution you'd like**
add eu.startpage.com and us.startpage.com to the list of supported search engines

**Describe alternatives you've considered**
using the default setting of "closest/fastest" server region

**Additional context**

**Comment by dmlls** [comment]
Hi @CrispyPin, good catch, a new release will be out soon.
