### ISSUE TITLE
Support https://karmasearch.org search engine in the extension

### ISSUE THREAD

**Issue by tomgar** [dmlls/yang#28]
Just that, please, add support for https://karmasearch.org to the extension. Thanks.

**Comment by dmlls** [comment]
Support added in [v0.9.32](https://github.com/dmlls/yang/releases/tag/v0.9.32). If you had the extension already installed, make sure that the new permissions for Karma Search are toggled on (you can find this in "Manage Extension → Permissions").

Thanks for reporting!
